// English translations
const enTranslations = {
    brandTitle: "Ather Foundation for Development",
    brandSub: "Livelihoods and Empowerment of Persons with Disabilities",
    navAbout: "About",
    navApproach: "Approach",
    navProjects: "Projects",
    navCfw: "Cash for Work",
    navResults: "Impact",
    navGallery: "Gallery",
    translateText: "العربية",
    pdfText: "Export PDF",
    heroBadge1: "Development Project in International Partnership",
    finlandBadge: "Funded by the Finnish Government",
    heroTitle: "Livelihoods and Empowerment of Persons with Disabilities",
    heroDesc: "A project reflecting Ather Foundation's commitment to transforming humanitarian aid into tangible development impact through economic and social empowerment.",
    heroBtn1: "View Impact & Results",
    heroBtn2: "Read Project Summary",
    meta1Label: "Duration",
    meta2Label: "Geographic Scope",
    meta3Label: "Direct Implementation",
    meta4Label: "Intervention Model",
    sideTitle1: "Why is this project important?",
    sideDesc1: "True empowerment goes beyond providing assistance; it opens a path to self-reliance.",
    pill1: "22 Direct Beneficiaries",
    pill2: "50 Households Visited",
    pill3: "9 Income-Generating Projects",
    pill4: "13 Persons with Disabilities Active in Community",
    centerName: "Give Us Hope Initiative",
    centerDesc: "Transforming an old building into a community center serving persons with disabilities",
    stat1Label: "Households Visited",
    stat1Note: "Home visits and needs assessment",
    stat2Label: "Final Beneficiaries",
    stat2Note: "8 Females & 14 Males",
    stat3Label: "Income-Generating Projects",
    stat3Note: "Targeted productive grants",
    stat4Label: "CfW Beneficiaries",
    stat4Note: "Rehabilitation of Empowerment Center",
    stat5Label: "Project Sustainability",
    stat5Note: "% by project end",
    stat6Label: "Grant Funding",
    stat6Note: "USD",
    aboutTitle: "About Ather Foundation & the Project",
    aboutSub: "Institutional framework reflecting the power of impact and partnerships.",
    about1Title: "Ather Foundation for Development",
    about1Desc: "A foundation working with a participatory development approach focused on capacity building.",
    about2Title: "Project Goal",
    about2Desc: "Enhancing economic and social empowerment of persons with disabilities.",
    about3Title: "Target Group",
    about3Desc: "Persons with physical, hearing, visual, and multiple disabilities.",
    about4Title: "Intervention Logic",
    about4Desc: "Combining productive grants and cash for work.",
    geoTitle: "Geographic Scope",
    geoSub: "Direct implementation in Khan Arnabeh.",
    approachTitle: "Implementation Methodology",
    approachSub: "A precise multi-stage methodology.",
    step1Title: "Survey & Assessment",
    step1Desc: "50 home visits and needs analysis.",
    step1Tag: "Phase 1",
    step2Title: "Selection & Screening",
    step2Desc: "Screening 22 beneficiaries according to vulnerability criteria.",
    step2Tag: "Precise Criteria",
    step3Title: "Dual Intervention",
    step3Desc: "Grants + Cash for Work.",
    step3Tag: "Dual Intervention",
    step4Title: "Follow-up & Closure",
    step4Desc: "Visits every 15 days and final evaluation.",
    step4Tag: "Sustainability",
    livelihoodTitle: "Livelihoods Program",
    livelihoodSub: "Diverse small projects.",
    trainTitle: "Training",
    trainDesc: "12 beneficiaries, 4 days in project management and marketing.",
    grantTitle: "Grant Value",
    grantDesc: "$2,400 per project, totaling $21,600.",
    followTitle: "Follow-up",
    followDesc: "Field visits every 15 days.",
    sustainTitle: "Sustainability",
    sustainDesc: "100% sustainability rate.",
    projectTypesTitle: "Funded Project Types",
    selectPrinciple: "Selection Principle",
    selectDesc: "Aligning project type with beneficiary experience.",
    techSupport: "Technical Support",
    techDesc: "Post-grant technical guidance.",
    cfwTitle: "Cash for Work Program",
    cfwSub: "Transforming cash incentives into community value.",
    cfwCount: "Number of Beneficiaries",
    cfwCountDesc: "13 beneficiaries, 2 days of training in occupational safety.",
    cfwIncentives: "Cash Incentives",
    cfwIncentivesDesc: "$360 per beneficiary, totaling $4,680.",
    cfwBudget: "Rehabilitation Budget",
    cfwBudgetDesc: "$5,000 for renovation and equipment.",
    cfwTotal: "Total",
    cfwTotalDesc: "Total CfW intervention: $9,680.",
    cfwWorksTitle: "Works Implemented in Give Us Hope Initiative",
    work1Title: "Needs Assessment",
    work1Desc: "Identifying technical priorities.",
    work2Title: "Renovation & Rehabilitation",
    work2Desc: "Improving functional readiness.",
    work3Title: "Interior Space Preparation",
    work3Desc: "Furnishing service spaces.",
    work4Title: "Procurement",
    work4Desc: "Providing necessary tools.",
    work5Title: "Educational Environment Setup",
    work5Desc: "Creating suitable spaces for persons with disabilities.",
    timelineMainTitle: "Project Timeline",
    timelineMainSub: "Detailed chronological sequence.",
    impactTitle: "Project Impact",
    impactSub: "Impact beyond numbers.",
    impactEconTitle: "Economic Impact",
    impactEcon1: "9 income-generating projects",
    impactEcon2: "Empowering 22 beneficiaries in the community",
    impactEcon3: "Funding worth $33,250",
    impactSocialTitle: "Social Impact",
    impactSocial1: "Integrating persons with disabilities",
    impactSocial2: "Improving access to services",
    impactSocial3: "Building confidence and self-reliance",
    impactInstTitle: "Institutional Impact",
    impactInst1: "Empowerment Center as a sustainable facility",
    impactInst2: "Dual intervention model",
    impactInst3: "Strengthening partnerships",
    financeTitle: "Financial Indicators",
    financeSub: "Clear summary of figures.",
    fin1Label: "Grant Funding",
    fin1Desc: "9 projects × $2,400",
    fin2Label: "Cash Incentives",
    fin2Desc: "13 beneficiaries × $360",
    fin3Label: "Rehabilitation Budget",
    fin3Desc: "Renovation & equipping Empowerment Center",
    fin4Label: "Total CfW",
    fin4Desc: "Incentives + Rehabilitation",
    galleryTitle: "Photo Gallery",
    gallerySub: "Visual documentation of the project.",
    galleryCap1: "Home visits & assessment",
    galleryCap2: "Livelihoods training",
    galleryCap3: "One of the grant projects",
    galleryCap4: "Empowerment Center rehabilitation",
    partnersTitle: "Success Partners",
    partnersSub: "Strategic partnership.",
    closingTitle: "Ather Foundation provides not just temporary intervention, but builds sustainable impact",
    closingDesc: "Ather has demonstrated its ability to implement complex interventions combining economic empowerment, transparent governance, and community rehabilitation.",
    closingPeriod: "Project Duration",
    closingBenef: "Direct Beneficiaries",
    closingFamilies: "Households Visited",
    closingSustainability: "Sustainability Rate",
    footerText1: "© 2026 Ather Foundation for Development | Livelihoods & Empowerment of Persons with Disabilities",
    footerText2: "Khan Arnabeh – Quneitra | Syrian Arab Republic",
    gov1: "Quneitra (Direct Implementation)",
    gov2: "Daraa",
    gov3: "Suwayda",
    gov4: "Damascus",
    gov5: "Rural Damascus",
    projType1: "Livestock Raising (2)",
    projType2: "Car Oil Change",
    projType3: "Grocery Store",
    projType4: "Electronics Repair",
    projType5: "Spice Shop",
    projType6: "Confectionery Making",
    projType7: "Construction Crane",
    projType8: "Household & Kitchen Items",
    card1Title: "Livestock Raising",
    card1Desc: "A project providing gradual income and utilizing local expertise.",
    card1Chip: "Income Generating",
    card2Title: "Grocery Store",
    card2Desc: "A practical option meeting daily market needs.",
    card2Chip: "Steady Demand",
    card3Title: "Electronics Repair",
    card3Desc: "A service needed in the local community.",
    card3Chip: "Technical Skills",
    card4Title: "Spice Shop",
    card4Desc: "A small project with manageable cost and profit margins.",
    card4Chip: "Fast Turnover",
    time1Title: "Assessment",
    time1Desc: "Conducting home visits and analyzing socio-economic needs.",
    time2Title: "Selection",
    time2Desc: "Screening final beneficiaries according to vulnerability criteria.",
    time3Title: "Training",
    time3Desc: "Implementing livelihoods and Cash for Work training.",
    time4Title: "Grant Implementation",
    time4Desc: "Procuring equipment and launching small income-generating projects.",
    time5Title: "Rehabilitation (CfW)",
    time5Desc: "Rehabilitating the Empowerment Center as a community facility.",
    time6Title: "Closure & Evaluation",
    time6Desc: "Completing documentation, measuring results, and preparing final report.",


// English translations - أضف هذه المفاتيح الجديدة في نهاية الكائن

    // ====== Hero Meta Values ======
    meta1Val: "01 / 10 / 2025 – 31 / 07 / 2026",
    meta2Val: "Quneitra, Daraa, Suwayda, Damascus, Rural Damascus",
    meta3Val: "Khan Arnabeh – Quneitra",
    meta4Val: "Grants + Cash for Work",
    
    // ====== Timeline Dates ======
    time1Date: "10 / 2025 – 11 / 2025",
    time2Date: "11 / 2025",
    time3Date: "12 / 2025 – 01 / 2026",
    time4Date: "02 / 2026 – 05 / 2026",
    time5Date: "03 / 2026 – 06 / 2026",
    time6Date: "07 / 2026",
    
    // ====== Closing Stats Values ======
    closingPeriodVal: "10/2025 – 07/2026",
    closingBenefVal: "22",
    closingFamiliesVal: "50",
    closingSustainabilityVal: "100%",
    
    // ====== Finance Values ======
    fin1Value: "$21,600",
    fin2Value: "$4,680",
    fin3Value: "$5,000",
    fin4Value: "$9,680",
};